// ============================================================
// ClassCraft English Vocabulary Data
// Structure: VOCAB['english'][examType][frequencyBand] = [{term, definition, hint, example}]
//
// Exam types:
//   'ielts-toefl'   IELTS / TOEFL academic vocabulary
//   'gre'           GRE verbal reasoning vocabulary
//
// Frequency bands:
//   'High Frequency'   — words that appear most often on exams
//   'Medium Frequency'  — words that appear regularly
//   'Low Frequency'     — less common but still tested words
//
// Each entry:
//   term       — the vocabulary word
//   definition — clear, concise meaning
//   hint       — short clue for hangman / study aids
//   example    — a real-style example sentence with the word replaced by ___
// ============================================================

VOCAB['english'] = VOCAB['english'] || {};

// ────────────────────────────────────────────────────────────
// IELTS / TOEFL — Academic English Vocabulary
// ────────────────────────────────────────────────────────────
VOCAB['english']['ielts-toefl'] = {

  'High Frequency': [
    { term:'analyse', definition:'To examine something in detail in order to explain or interpret it.', hint:'Break down to understand', example:'Researchers ___ the data collected from the survey to identify key trends.' },
    { term:'approach', definition:'A way of dealing with a situation or problem.', hint:'Method or strategy', example:'The government adopted a new ___ to tackling climate change.' },
    { term:'assess', definition:'To evaluate or estimate the nature, quality, or ability of something.', hint:'Judge or evaluate', example:'Teachers ___ student performance through a combination of exams and coursework.' },
    { term:'assume', definition:'To accept something as true without proof.', hint:'Take for granted', example:'Many people ___ that economic growth always leads to improved living standards.' },
    { term:'authority', definition:'The power or right to give orders, make decisions, or enforce rules.', hint:'Power to control', example:'The local ___ imposed new regulations on building development.' },
    { term:'available', definition:'Able to be used or obtained; at hand.', hint:'Ready to use', example:'Scholarships are ___ for students who demonstrate exceptional academic ability.' },
    { term:'benefit', definition:'An advantage or profit gained from something.', hint:'Advantage or gain', example:'One major ___ of regular exercise is improved mental health.' },
    { term:'concept', definition:'An abstract idea or general notion.', hint:'An idea or principle', example:'The ___ of sustainable development has gained widespread acceptance.' },
    { term:'consistent', definition:'Acting or done in the same way over time; unchanging.', hint:'Steady and reliable', example:'The results were ___ across all three experiments, confirming the hypothesis.' },
    { term:'constitute', definition:'To be a part of a whole; to form or compose.', hint:'Make up or form', example:'Women ___ approximately half of the global workforce.' },
    { term:'context', definition:'The circumstances or setting in which an event occurs.', hint:'Background or setting', example:'The meaning of the word changes depending on the ___ in which it is used.' },
    { term:'contribute', definition:'To give something in order to help achieve or provide something.', hint:'Add to or help with', example:'Several factors ___ to the rise in global temperatures.' },
    { term:'create', definition:'To bring something into existence.', hint:'Make or produce', example:'The new policy aims to ___ more opportunities for young entrepreneurs.' },
    { term:'data', definition:'Facts and statistics collected for reference or analysis.', hint:'Information or facts', example:'The ___ suggest that air pollution levels have decreased over the past decade.' },
    { term:'define', definition:'To state the exact meaning or scope of something.', hint:'Give the meaning of', example:'It is important to clearly ___ the terms used in any research paper.' },
    { term:'derive', definition:'To obtain something from a specified source.', hint:'Get from a source', example:'Many English words ___ from Latin and Greek roots.' },
    { term:'distribute', definition:'To give shares of something or spread it over an area.', hint:'Spread out or share', example:'Aid agencies worked to ___ food supplies to the affected regions.' },
    { term:'economy', definition:'The state of a country in terms of the production and consumption of goods.', hint:'System of wealth and trade', example:'The global ___ experienced a significant downturn during the pandemic.' },
    { term:'environment', definition:'The surroundings or conditions in which a person, animal, or plant lives.', hint:'Natural world or surroundings', example:'Deforestation has a devastating impact on the natural ___.' },
    { term:'establish', definition:'To set up on a firm or permanent basis.', hint:'Set up or found', example:'The university was ___ in 1850 and has grown significantly since then.' },
    { term:'estimate', definition:'To roughly calculate or judge the value, number, or extent of something.', hint:'Make an educated guess', example:'Experts ___ that the world population will reach ten billion by 2050.' },
    { term:'evident', definition:'Clearly seen or understood; obvious.', hint:'Clear or obvious', example:'It is ___ from the research that early intervention leads to better outcomes.' },
    { term:'factor', definition:'A circumstance or element that contributes to a result.', hint:'Contributing element', example:'Diet is a significant ___ in the prevention of heart disease.' },
    { term:'function', definition:'The purpose or role that something has or is expected to have.', hint:'Purpose or role', example:'The primary ___ of the liver is to filter toxins from the blood.' },
    { term:'identify', definition:'To recognise or establish what something is.', hint:'Recognise or pinpoint', example:'Scientists have been able to ___ the gene responsible for the condition.' },
    { term:'impact', definition:'A marked effect or influence.', hint:'Strong effect', example:'Technology has had a profound ___ on the way people communicate.' },
    { term:'indicate', definition:'To point out or show.', hint:'Show or suggest', example:'Recent studies ___ that sleep deprivation can seriously affect cognitive function.' },
    { term:'individual', definition:'A single human being, distinct from a group.', hint:'Single person', example:'Each ___ is responsible for reducing their own carbon footprint.' },
    { term:'interpret', definition:'To explain the meaning of information or actions.', hint:'Explain the meaning', example:'Historians ___ the evidence in different ways depending on their perspective.' },
    { term:'involve', definition:'To include as a necessary part or result.', hint:'Include or require', example:'The project will ___ collaboration between multiple departments.' },
    { term:'issue', definition:'An important topic or problem for debate or discussion.', hint:'Topic or problem', example:'Climate change remains one of the most pressing ___ of our time.' },
    { term:'labour', definition:'Work, especially physical work; the workforce.', hint:'Work or workers', example:'The country faces a shortage of skilled ___ in the technology sector.' },
    { term:'legal', definition:'Relating to the law; permitted by law.', hint:'Related to law', example:'All employees have ___ rights that protect them from unfair dismissal.' },
    { term:'legislate', definition:'To make or enact laws.', hint:'Make laws', example:'The government plans to ___ against the use of single-use plastics.' },
    { term:'major', definition:'Important, serious, or significant.', hint:'Important or big', example:'Urbanisation is a ___ trend affecting developing countries worldwide.' },
    { term:'method', definition:'A particular way of doing something, especially a systematic one.', hint:'Way of doing things', example:'The scientific ___ involves forming hypotheses and testing them through experimentation.' },
    { term:'occur', definition:'To happen or take place.', hint:'Happen', example:'Earthquakes ___ more frequently along tectonic plate boundaries.' },
    { term:'percent', definition:'One part in every hundred.', hint:'Out of a hundred', example:'Approximately 70 ___ of the Earth\'s surface is covered by water.' },
    { term:'period', definition:'A length or portion of time.', hint:'Span of time', example:'The post-war ___ saw rapid economic growth in many Western nations.' },
    { term:'policy', definition:'A course of action adopted by a government, organisation, or individual.', hint:'Plan of action', example:'The new education ___ focuses on improving literacy rates among young children.' },
    { term:'principle', definition:'A fundamental truth or proposition that serves as the foundation for reasoning.', hint:'Basic truth or rule', example:'The ___ of supply and demand is central to economic theory.' },
    { term:'proceed', definition:'To begin or continue a course of action.', hint:'Go ahead or continue', example:'After the safety checks, the team decided to ___ with the experiment.' },
    { term:'process', definition:'A series of actions or steps taken to achieve a particular end.', hint:'Series of steps', example:'The ___ of applying for a visa can be lengthy and complex.' },
    { term:'require', definition:'To need something as a necessity.', hint:'Need', example:'All applicants ___ a minimum score of 6.5 on the IELTS examination.' },
    { term:'research', definition:'The systematic investigation into and study of materials and sources.', hint:'Systematic study', example:'Further ___ is needed to understand the long-term effects of the treatment.' },
    { term:'respond', definition:'To say or do something as a reaction to something.', hint:'React or reply', example:'The government was slow to ___ to the growing crisis.' },
    { term:'role', definition:'The function assumed or part played by a person or thing.', hint:'Part played', example:'Education plays a crucial ___ in reducing poverty and inequality.' },
    { term:'section', definition:'Any of the more or less distinct parts into which something is divided.', hint:'Part or segment', example:'The reading ___ of the exam tests comprehension and analytical skills.' },
    { term:'significant', definition:'Sufficiently great or important to be worthy of attention.', hint:'Important or notable', example:'There has been a ___ increase in renewable energy production over the past decade.' },
    { term:'similar', definition:'Resembling without being identical.', hint:'Alike but not the same', example:'The two studies reached ___ conclusions despite using different methodologies.' },
    { term:'source', definition:'A place, person, or thing from which something originates.', hint:'Origin or starting point', example:'Fossil fuels remain the primary ___ of energy in many countries.' },
    { term:'specific', definition:'Clearly defined or identified; precise.', hint:'Exact or particular', example:'The report made ___ recommendations for improving public transport.' },
    { term:'structure', definition:'The arrangement of and relations between the parts of something complex.', hint:'How parts are organised', example:'The ___ of the essay should include an introduction, body, and conclusion.' },
    { term:'theory', definition:'A system of ideas intended to explain something, based on general principles.', hint:'Explanation based on evidence', example:'Darwin\'s ___ of evolution revolutionised the field of biology.' },
    { term:'vary', definition:'To differ in size, amount, degree, or nature.', hint:'Change or differ', example:'Opinions on the matter ___ widely among experts in the field.' },
  ],

  'Medium Frequency': [
    { term:'accumulate', definition:'To gather together or acquire an increasing amount of something.', hint:'Build up over time', example:'Debt can ___ quickly if repayments are not made on time.' },
    { term:'adequate', definition:'Sufficient for a specific requirement; acceptable.', hint:'Enough or sufficient', example:'The school lacked ___ funding to maintain its facilities properly.' },
    { term:'adjacent', definition:'Next to or adjoining something else.', hint:'Next to', example:'The new hospital was built on land ___ to the university campus.' },
    { term:'advocate', definition:'To publicly recommend or support a particular cause or policy.', hint:'Publicly support', example:'Many health organisations ___ for stricter regulations on sugary drinks.' },
    { term:'allocate', definition:'To distribute resources or duties for a particular purpose.', hint:'Assign or set aside', example:'The council decided to ___ more funds to public housing projects.' },
    { term:'ambiguous', definition:'Open to more than one interpretation; not clear.', hint:'Unclear in meaning', example:'The wording of the contract was ___, leading to a legal dispute.' },
    { term:'annual', definition:'Occurring once every year.', hint:'Yearly', example:'The company publishes an ___ report detailing its financial performance.' },
    { term:'apparent', definition:'Clearly visible or understood; obvious.', hint:'Seemingly clear', example:'It became ___ that the project would not be completed on time.' },
    { term:'arbitrary', definition:'Based on random choice rather than reason or system.', hint:'Random or without reason', example:'The decision to close the park seemed ___ and upset many residents.' },
    { term:'attribute', definition:'To regard something as being caused by; a quality or feature.', hint:'Credit to or a quality', example:'Historians ___ the fall of the empire to a combination of internal and external factors.' },
    { term:'cease', definition:'To come or bring to an end.', hint:'Stop completely', example:'Hostilities between the two nations ___ after the peace agreement was signed.' },
    { term:'coherent', definition:'Logical and consistent; forming a unified whole.', hint:'Logical and connected', example:'The student presented a ___ argument supported by strong evidence.' },
    { term:'coincide', definition:'To occur at the same time or place.', hint:'Happen at the same time', example:'The festival is timed to ___ with the summer solstice.' },
    { term:'comprehensive', definition:'Including all or nearly all elements or aspects of something.', hint:'Complete and thorough', example:'The report provides a ___ overview of the current state of the healthcare system.' },
    { term:'conclude', definition:'To bring something to an end; to reach a judgement after reasoning.', hint:'Finish or decide', example:'The researchers ___ that the new treatment is more effective than the existing one.' },
    { term:'contradict', definition:'To deny the truth of a statement by asserting the opposite.', hint:'Say the opposite', example:'The new findings ___ the results of earlier studies on the same topic.' },
    { term:'crucial', definition:'Of great importance, especially in the success of something.', hint:'Extremely important', example:'Access to clean water is ___ for the health and development of communities.' },
    { term:'decline', definition:'To become smaller, fewer, or less; to decrease.', hint:'Go down or reduce', example:'The population of many bird species has ___ sharply due to habitat loss.' },
    { term:'demonstrate', definition:'To clearly show the existence or truth of something.', hint:'Show or prove', example:'The experiment was designed to ___ the effects of temperature on plant growth.' },
    { term:'deviate', definition:'To depart from an established course or norm.', hint:'Stray from the norm', example:'The results did not ___ significantly from what was predicted by the model.' },
    { term:'diminish', definition:'To make or become less; to reduce.', hint:'Lessen or reduce', example:'The influence of traditional media has ___ with the rise of social networks.' },
    { term:'distinct', definition:'Recognisably different in nature from something else.', hint:'Clearly different', example:'There are two ___ approaches to solving this mathematical problem.' },
    { term:'domestic', definition:'Relating to the running of a home; existing within a particular country.', hint:'Home or national', example:'The government prioritised ___ issues over foreign policy during the election campaign.' },
    { term:'dominate', definition:'To have a commanding influence on; to be the most important element.', hint:'Control or prevail', example:'A few large corporations ___ the global technology market.' },
    { term:'draft', definition:'A preliminary version of a piece of writing; to prepare a preliminary version.', hint:'First version', example:'Students are encouraged to write a ___ before submitting their final essay.' },
    { term:'eliminate', definition:'To completely remove or get rid of something.', hint:'Remove entirely', example:'The new policy aims to ___ all forms of workplace discrimination.' },
    { term:'emerge', definition:'To come into view or existence; to become apparent.', hint:'Come out or appear', example:'New evidence has ___ that challenges the previously accepted theory.' },
    { term:'empirical', definition:'Based on observation or experience rather than theory or logic.', hint:'Based on real-world evidence', example:'The study relied on ___ data gathered through extensive fieldwork.' },
    { term:'enhance', definition:'To intensify, increase, or further improve the quality of something.', hint:'Make better or improve', example:'Technology can ___ the learning experience when used effectively in the classroom.' },
    { term:'enormous', definition:'Very large in size, quantity, or extent.', hint:'Extremely big', example:'The project required an ___ investment of both time and money.' },
    { term:'facilitate', definition:'To make an action or process easy or easier.', hint:'Make easier', example:'The new software was designed to ___ communication between team members.' },
    { term:'fluctuate', definition:'To rise and fall irregularly in number or amount.', hint:'Go up and down', example:'Oil prices tend to ___ in response to changes in global supply and demand.' },
    { term:'furthermore', definition:'In addition; besides (used to introduce a further point).', hint:'In addition', example:'The proposal is cost-effective; ___, it has strong community support.' },
    { term:'generate', definition:'To cause something to arise or come about; to produce.', hint:'Produce or create', example:'Solar panels ___ electricity by converting sunlight into energy.' },
    { term:'hypothesis', definition:'A proposed explanation made on the basis of limited evidence as a starting point.', hint:'Educated guess to test', example:'The ___ was tested through a series of controlled experiments.' },
    { term:'implement', definition:'To put a decision, plan, or agreement into effect.', hint:'Put into action', example:'The school plans to ___ a new anti-bullying policy next term.' },
    { term:'implicit', definition:'Suggested though not directly expressed; inherent.', hint:'Implied, not stated', example:'There was an ___ understanding between the parties that the deal would proceed.' },
    { term:'incidence', definition:'The occurrence, rate, or frequency of a disease, condition, or event.', hint:'Rate of occurrence', example:'The ___ of diabetes has risen dramatically in developed countries.' },
    { term:'infrastructure', definition:'The basic physical systems of a country or organisation, such as transport and power.', hint:'Basic systems and structures', example:'Investing in ___ is essential for long-term economic development.' },
    { term:'inherent', definition:'Existing in something as a permanent or essential quality.', hint:'Built-in or natural', example:'There are ___ risks associated with any surgical procedure.' },
    { term:'inhibit', definition:'To hinder, restrain, or prevent an action or process.', hint:'Hold back or prevent', example:'Lack of funding can ___ scientific progress in developing nations.' },
    { term:'innovation', definition:'A new method, idea, or product.', hint:'New idea or invention', example:'Technological ___ has transformed the way businesses operate globally.' },
    { term:'integrate', definition:'To combine one thing with another to form a whole.', hint:'Combine into one', example:'The curriculum aims to ___ technology into every subject area.' },
    { term:'invoke', definition:'To cite or appeal to someone or something as an authority.', hint:'Call upon or cite', example:'The lawyer chose to ___ a rarely used statute in the defence argument.' },
    { term:'isolate', definition:'To set apart from others; to identify something separately.', hint:'Separate or set apart', example:'Scientists managed to ___ the virus responsible for the outbreak.' },
    { term:'justify', definition:'To show or prove to be right or reasonable.', hint:'Give reasons for', example:'The company struggled to ___ the sudden increase in prices to its customers.' },
    { term:'liberal', definition:'Open to new behaviour or opinions; favouring individual liberty.', hint:'Open-minded or progressive', example:'The university is known for its ___ approach to academic freedom.' },
    { term:'likewise', definition:'In the same way; also.', hint:'Similarly', example:'The first experiment showed positive results; ___, the second confirmed the trend.' },
    { term:'maintain', definition:'To cause or enable a condition or situation to continue.', hint:'Keep going or preserve', example:'It is important to ___ a balanced diet for overall good health.' },
    { term:'mechanism', definition:'A system of parts working together; a natural or established process.', hint:'How something works', example:'The ___ by which the drug reduces inflammation is not yet fully understood.' },
  ],

  'Low Frequency': [
    { term:'abstract', definition:'Existing in thought or as an idea but not having a physical existence.', hint:'Theoretical, not concrete', example:'The concept of justice is highly ___ and varies across cultures.' },
    { term:'albeit', definition:'Although; even though.', hint:'Even though', example:'The results were promising, ___ based on a relatively small sample size.' },
    { term:'analogy', definition:'A comparison between one thing and another for the purpose of explanation.', hint:'Comparison for clarity', example:'The teacher used an ___ of a factory to explain how a cell functions.' },
    { term:'anomaly', definition:'Something that deviates from what is standard, normal, or expected.', hint:'Something unusual', example:'The sudden temperature drop was an ___ that could not be explained by existing models.' },
    { term:'anticipate', definition:'To regard as probable; to expect or predict.', hint:'Expect in advance', example:'Economists ___ a slowdown in growth during the coming quarter.' },
    { term:'compile', definition:'To produce a list or document by assembling information from other sources.', hint:'Gather and assemble', example:'The team worked for months to ___ a comprehensive database of climate records.' },
    { term:'complement', definition:'A thing that contributes extra features to something else to enhance it.', hint:'Add to and improve', example:'The new wing of the museum was designed to ___ the existing architecture.' },
    { term:'concurrent', definition:'Existing, happening, or done at the same time.', hint:'At the same time', example:'The study ran ___ experiments in three different laboratories.' },
    { term:'confine', definition:'To keep or restrict someone or something within certain limits.', hint:'Restrict or limit', example:'The discussion should be ___ to the topic at hand to ensure productivity.' },
    { term:'consensus', definition:'A general agreement among a group.', hint:'Shared agreement', example:'There is a growing ___ among scientists that human activity is driving climate change.' },
    { term:'controversy', definition:'Prolonged public disagreement or heated discussion.', hint:'Public debate or dispute', example:'The proposed dam project sparked considerable ___ among environmental groups.' },
    { term:'convene', definition:'To come together or assemble for a meeting or activity.', hint:'Gather for a meeting', example:'The committee will ___ next week to discuss the proposed changes to the curriculum.' },
    { term:'denote', definition:'To be a sign of; to indicate.', hint:'Mean or indicate', example:'In this chart, red shading is used to ___ areas with the highest pollution levels.' },
    { term:'deplete', definition:'To use up the supply or resources of something.', hint:'Use up or exhaust', example:'Overfishing threatens to ___ fish stocks in many of the world\'s oceans.' },
    { term:'displace', definition:'To take over the place, position, or role of something or someone.', hint:'Force out of position', example:'Automation is expected to ___ millions of workers in the manufacturing sector.' },
    { term:'erode', definition:'To gradually wear away or diminish.', hint:'Wear away slowly', example:'Public trust in institutions can ___ when transparency is lacking.' },
    { term:'excerpt', definition:'A short extract from a piece of writing or music.', hint:'Short passage from a text', example:'The lecturer read an ___ from the original publication to illustrate the point.' },
    { term:'exploit', definition:'To make full use of a resource; to use unfairly for one\'s own advantage.', hint:'Use fully or take advantage of', example:'Companies that ___ natural resources without regulation cause lasting environmental damage.' },
    { term:'foremost', definition:'Most prominent in rank, importance, or position.', hint:'Leading or first', example:'She is regarded as one of the ___ experts in marine biology.' },
    { term:'forthcoming', definition:'About to happen or appear; willing to provide information.', hint:'Coming soon or open', example:'Details of the new policy will be released in the ___ report.' },
    { term:'hierarchy', definition:'A system in which members are ranked according to relative status or authority.', hint:'Ranking system', example:'The ___ within the organisation determines how decisions are made.' },
    { term:'ideology', definition:'A system of ideas and ideals, especially one that forms the basis of policy.', hint:'Set of beliefs or ideas', example:'Political ___ plays a significant role in shaping government policy.' },
    { term:'inclination', definition:'A tendency or disposition to act in a particular way.', hint:'Tendency or preference', example:'Students showed a strong ___ towards collaborative learning methods.' },
    { term:'integrity', definition:'The quality of being honest and having strong moral principles; the state of being whole.', hint:'Honesty or wholeness', example:'The ___ of the data must be preserved throughout the research process.' },
    { term:'mediate', definition:'To intervene in a dispute in order to bring about an agreement.', hint:'Help resolve a conflict', example:'A neutral third party was brought in to ___ between the two sides.' },
    { term:'negate', definition:'To nullify or make ineffective.', hint:'Cancel out', example:'The positive effects of the treatment were ___ by the severe side effects.' },
    { term:'notwithstanding', definition:'In spite of; nevertheless.', hint:'Despite', example:'___ the challenges, the project was completed ahead of schedule.' },
    { term:'offset', definition:'To counteract something by having an equal and opposite effect.', hint:'Balance out', example:'The company planted trees to ___ its carbon emissions from manufacturing.' },
    { term:'paradigm', definition:'A typical example or pattern of something; a model or framework.', hint:'Model or framework', example:'The discovery led to a ___ shift in how scientists understood the disease.' },
    { term:'precede', definition:'To come before something in time, order, or position.', hint:'Come before', example:'A brief period of economic stability ___ the major financial crisis.' },
    { term:'presumption', definition:'An idea that is taken to be true without verification.', hint:'Assumption', example:'The ___ of innocence is a fundamental principle of the legal system.' },
    { term:'prospective', definition:'Expected or expecting to be something particular in the future.', hint:'Potential or future', example:'___ students are invited to attend the open day this Saturday.' },
    { term:'rationale', definition:'A set of reasons or a logical basis for a course of action.', hint:'Reasoning behind something', example:'The ___ behind the decision was explained in detail during the meeting.' },
    { term:'relinquish', definition:'To voluntarily give up or cease to hold something.', hint:'Give up willingly', example:'The CEO was reluctant to ___ control of the company he had founded.' },
    { term:'salient', definition:'Most noticeable or important; prominent.', hint:'Standing out or key', example:'The report highlighted the most ___ findings from the year-long investigation.' },
    { term:'scrutiny', definition:'Critical observation or examination.', hint:'Close inspection', example:'Government spending is under increasing ___ from independent auditors.' },
    { term:'subordinate', definition:'Lower in rank or position; to treat as less important.', hint:'Lower in rank', example:'In many traditional organisations, ___ staff have limited input into decision-making.' },
    { term:'subsequent', definition:'Coming after something in time; following.', hint:'Following after', example:'The initial study and all ___ research confirmed the original findings.' },
    { term:'supplement', definition:'Something added to complete or enhance something else.', hint:'Addition or extra', example:'Many athletes take dietary ___ to improve their performance.' },
    { term:'undermine', definition:'To erode the base or foundation of; to weaken gradually.', hint:'Weaken from beneath', example:'Persistent rumours began to ___ public confidence in the institution.' },
  ],
};

// ────────────────────────────────────────────────────────────
// GRE — Graduate Record Examination Vocabulary
// ────────────────────────────────────────────────────────────
VOCAB['english']['gre'] = {

  'High Frequency': [
    { term:'aberrant', definition:'Departing from an accepted standard; deviating from the norm.', hint:'Abnormal or deviant', example:'The scientist noted the ___ results and decided to repeat the experiment.' },
    { term:'acumen', definition:'The ability to make good judgements and quick decisions, especially in business.', hint:'Sharp judgement', example:'Her financial ___ helped the startup secure its first round of funding.' },
    { term:'aesthetic', definition:'Concerned with beauty or the appreciation of beauty.', hint:'Related to beauty', example:'The architect was praised for the ___ qualities of the new museum design.' },
    { term:'alleviate', definition:'To make suffering, a problem, or a deficiency less severe.', hint:'Reduce or relieve', example:'The charity works to ___ poverty in rural communities through education programmes.' },
    { term:'amalgamate', definition:'To combine or unite to form one structure or organisation.', hint:'Merge together', example:'The two departments were ___ to improve efficiency and reduce overhead costs.' },
    { term:'ambivalent', definition:'Having mixed feelings or contradictory ideas about something.', hint:'Torn between two views', example:'She felt ___ about moving abroad, excited by the opportunity but sad to leave home.' },
    { term:'analogous', definition:'Comparable in certain respects, typically in a way that makes clearer the nature of the things compared.', hint:'Similar or comparable', example:'The relationship between a CEO and a company is ___ to that of a captain and a ship.' },
    { term:'anomalous', definition:'Deviating from what is standard, normal, or expected.', hint:'Irregular or unusual', example:'The ___ weather patterns were attributed to shifting ocean currents.' },
    { term:'antipathy', definition:'A deep-seated feeling of aversion or dislike.', hint:'Strong dislike', example:'His ___ towards bureaucratic procedures was well known among his colleagues.' },
    { term:'apathy', definition:'Lack of interest, enthusiasm, or concern.', hint:'Indifference', example:'Voter ___ has been identified as a major problem in recent elections.' },
    { term:'arduous', definition:'Involving or requiring strenuous effort; difficult and tiring.', hint:'Very difficult', example:'The ___ journey through the mountains took the explorers three full weeks.' },
    { term:'articulate', definition:'Having or showing the ability to speak fluently and coherently.', hint:'Well-spoken', example:'She is an exceptionally ___ speaker who can explain complex ideas with great clarity.' },
    { term:'austere', definition:'Severe or strict in manner or attitude; having no comforts or luxuries.', hint:'Strict and plain', example:'The monastery was known for its ___ living conditions and rigorous daily routine.' },
    { term:'bolster', definition:'To support, strengthen, or reinforce something.', hint:'Prop up or support', example:'The new evidence served to ___ the prosecution\'s case against the defendant.' },
    { term:'burgeon', definition:'To begin to grow or increase rapidly; to flourish.', hint:'Grow rapidly', example:'Interest in renewable energy has ___ over the past decade as costs have fallen.' },
    { term:'candid', definition:'Truthful and straightforward; frank.', hint:'Honest and direct', example:'The CEO gave a ___ assessment of the company\'s financial difficulties.' },
    { term:'capricious', definition:'Given to sudden and unaccountable changes of mood or behaviour.', hint:'Unpredictable', example:'The ___ nature of the weather made it difficult to plan outdoor events.' },
    { term:'cogent', definition:'Clear, logical, and convincing.', hint:'Persuasive argument', example:'The lawyer presented a ___ argument that swayed the opinion of the jury.' },
    { term:'commensurate', definition:'Corresponding in size or degree; in proportion.', hint:'Proportional', example:'Employees expect salaries ___ with their level of experience and qualifications.' },
    { term:'contentious', definition:'Causing or likely to cause an argument; controversial.', hint:'Arguable or disputed', example:'The allocation of funding has always been a ___ issue within the committee.' },
    { term:'convoluted', definition:'Extremely complex and difficult to follow.', hint:'Overly complicated', example:'The ___ plot of the novel confused many readers who struggled to follow its twists.' },
    { term:'corroborate', definition:'To confirm or give support to a statement, theory, or finding.', hint:'Confirm or back up', example:'Witnesses were called to ___ the account given by the victim.' },
    { term:'credulous', definition:'Having or showing too great a readiness to believe things.', hint:'Too easily convinced', example:'___ investors were taken in by the fraudulent scheme promising unrealistic returns.' },
    { term:'dearth', definition:'A scarcity or lack of something.', hint:'Shortage', example:'There is a ___ of qualified teachers in many rural areas of the country.' },
    { term:'debilitate', definition:'To make someone very weak and infirm.', hint:'Severely weaken', example:'The illness continued to ___ the patient despite months of treatment.' },
    { term:'decorum', definition:'Behaviour in keeping with good taste and propriety; etiquette.', hint:'Proper behaviour', example:'Guests were expected to maintain a sense of ___ during the formal dinner.' },
    { term:'delineate', definition:'To describe or portray something precisely.', hint:'Outline clearly', example:'The report carefully ___ the boundaries between the two jurisdictions.' },
    { term:'denigrate', definition:'To criticise unfairly; to disparage.', hint:'Belittle or put down', example:'Political opponents attempted to ___ her reputation through misleading claims.' },
    { term:'didactic', definition:'Intended to teach, especially in a way perceived as overly instructive.', hint:'Preachy or instructional', example:'The novel was criticised for being too ___, lecturing readers rather than engaging them.' },
    { term:'disparate', definition:'Essentially different in kind; not able to be compared.', hint:'Fundamentally different', example:'The study drew on ___ sources, ranging from ancient texts to modern data sets.' },
    { term:'dogmatic', definition:'Inclined to lay down principles as undeniably true, without consideration of evidence.', hint:'Rigid in belief', example:'His ___ approach to management left no room for alternative viewpoints.' },
    { term:'ebullient', definition:'Cheerful and full of energy; enthusiastic.', hint:'Bubbly and excited', example:'The ___ crowd erupted in celebration when the final goal was scored.' },
    { term:'efficacious', definition:'Successful in producing a desired or intended result; effective.', hint:'Effective', example:'The vaccine proved to be highly ___ in clinical trials conducted across multiple countries.' },
    { term:'egregious', definition:'Outstandingly bad; shocking.', hint:'Shockingly terrible', example:'The report uncovered ___ violations of safety regulations at the factory.' },
    { term:'elicit', definition:'To evoke or draw out a response, answer, or fact from someone.', hint:'Draw out', example:'The teacher\'s question was designed to ___ a deeper understanding of the text.' },
    { term:'eloquent', definition:'Fluent or persuasive in speaking or writing.', hint:'Movingly expressive', example:'The ambassador delivered an ___ speech calling for international cooperation.' },
    { term:'empirical', definition:'Based on observation or experience rather than theory or pure logic.', hint:'Based on evidence', example:'The conclusions were supported by ___ evidence gathered over a five-year period.' },
    { term:'engender', definition:'To cause or give rise to a feeling, situation, or condition.', hint:'Give rise to', example:'The policy was intended to ___ a sense of trust between the government and citizens.' },
    { term:'enigmatic', definition:'Difficult to interpret or understand; mysterious.', hint:'Puzzling or mysterious', example:'The ___ smile of the portrait has fascinated art historians for centuries.' },
    { term:'enumerate', definition:'To mention a number of things one by one.', hint:'List out', example:'The speaker proceeded to ___ the key factors contributing to the economic recovery.' },
    { term:'ephemeral', definition:'Lasting for a very short time.', hint:'Brief and fleeting', example:'Social media fame is often ___, with trends disappearing as quickly as they emerge.' },
    { term:'equivocal', definition:'Open to more than one interpretation; ambiguous.', hint:'Unclear or vague', example:'The politician gave an ___ answer that failed to satisfy reporters seeking clarity.' },
    { term:'exacerbate', definition:'To make a problem, bad situation, or negative feeling worse.', hint:'Make worse', example:'Rising temperatures are expected to ___ water shortages in arid regions.' },
    { term:'exonerate', definition:'To absolve someone from blame for a fault or wrongdoing.', hint:'Clear of blame', example:'New DNA evidence served to ___ the man who had been wrongfully imprisoned.' },
    { term:'extrapolate', definition:'To extend the application of something to an unknown situation by assuming existing trends will continue.', hint:'Project from known data', example:'Scientists ___ from current trends to predict future sea-level changes.' },
  ],

  'Medium Frequency': [
    { term:'facetious', definition:'Treating serious issues with deliberately inappropriate humour.', hint:'Inappropriately joking', example:'His ___ remarks during the meeting were not appreciated by the senior partners.' },
    { term:'fallacious', definition:'Based on a mistaken belief; containing a logical error.', hint:'Logically flawed', example:'The argument was ___, relying on a correlation that did not imply causation.' },
    { term:'fervid', definition:'Intensely enthusiastic or passionate, especially to an excessive degree.', hint:'Intensely passionate', example:'The ___ supporters of the movement organised protests across the country.' },
    { term:'garrulous', definition:'Excessively talkative, especially on trivial matters.', hint:'Overly chatty', example:'The ___ passenger talked nonstop for the entire duration of the flight.' },
    { term:'germane', definition:'Relevant to a subject under consideration.', hint:'On-topic or relevant', example:'The judge ruled that the evidence was not ___ to the case and should be excluded.' },
    { term:'gregarious', definition:'Fond of company; sociable.', hint:'Very sociable', example:'Her ___ personality made her the natural choice to lead the welcoming committee.' },
    { term:'harangue', definition:'A lengthy and aggressive speech; to lecture aggressively.', hint:'Aggressive rant', example:'The manager ___ the team about their declining performance for over an hour.' },
    { term:'iconoclast', definition:'A person who attacks cherished beliefs or institutions.', hint:'Challenger of traditions', example:'The philosopher was considered an ___ for rejecting the dominant theories of his era.' },
    { term:'impervious', definition:'Not allowing fluid to pass through; unable to be affected.', hint:'Resistant to influence', example:'The material was ___ to water, making it ideal for outdoor construction.' },
    { term:'inchoate', definition:'Just begun and so not fully formed or developed; rudimentary.', hint:'In early stages', example:'The plan was still in an ___ stage and needed considerable refinement.' },
    { term:'inexorable', definition:'Impossible to stop or prevent; relentless.', hint:'Unstoppable', example:'The ___ rise of sea levels poses a serious threat to coastal communities.' },
    { term:'insipid', definition:'Lacking flavour, vigour, or interest.', hint:'Dull and bland', example:'Critics described the novel as ___, lacking the depth and originality of the author\'s earlier work.' },
    { term:'intransigent', definition:'Unwilling or refusing to change one\'s views or to agree about something.', hint:'Stubbornly unyielding', example:'The ___ negotiators refused to make any concessions during the peace talks.' },
    { term:'laconic', definition:'Using very few words; brief and concise.', hint:'Extremely brief', example:'His ___ reply of a single word left the interviewer unsure how to continue.' },
    { term:'laud', definition:'To praise highly, especially in a public context.', hint:'Praise greatly', example:'The critics ___ the director\'s latest film as a masterpiece of modern cinema.' },
    { term:'lethargic', definition:'Affected by a lack of energy or enthusiasm; sluggish.', hint:'Very tired and slow', example:'The hot weather made the students feel ___ and unable to concentrate during class.' },
    { term:'lucid', definition:'Expressed clearly; easy to understand.', hint:'Clear and easy to follow', example:'Despite the complexity of the topic, the professor gave a remarkably ___ explanation.' },
    { term:'magnanimous', definition:'Generous or forgiving, especially towards a rival or less powerful person.', hint:'Noble and generous', example:'In a ___ gesture, the winner donated the prize money to a local charity.' },
    { term:'mercurial', definition:'Subject to sudden or unpredictable changes of mood or mind.', hint:'Changeable', example:'Her ___ temperament made it difficult for colleagues to predict her reactions.' },
    { term:'meticulous', definition:'Showing great attention to detail; very careful and precise.', hint:'Extremely careful', example:'The restoration of the painting required ___ attention to every brushstroke.' },
    { term:'mitigate', definition:'To make something less severe, serious, or painful.', hint:'Lessen the severity', example:'Flood barriers were constructed to ___ the risk of damage to riverside properties.' },
    { term:'obdurate', definition:'Stubbornly refusing to change one\'s opinion or course of action.', hint:'Stubbornly unyielding', example:'Despite widespread criticism, the leader remained ___ in her decision to proceed.' },
    { term:'obsequious', definition:'Obedient or attentive to an excessive degree; servile.', hint:'Overly submissive', example:'The ___ assistant agreed with everything the director said without question.' },
    { term:'opaque', definition:'Not able to be seen through; not transparent. Also: difficult to understand.', hint:'Hard to see through or understand', example:'The company\'s ___ financial reporting raised concerns among regulators.' },
    { term:'ostensible', definition:'Stated or appearing to be true, but not necessarily so.', hint:'Seemingly true', example:'The ___ reason for the meeting was a budget review, but the real agenda was restructuring.' },
    { term:'parsimonious', definition:'Very unwilling to spend money or use resources; extremely frugal.', hint:'Extremely stingy', example:'The ___ landlord refused to repair the leaking roof despite numerous complaints.' },
    { term:'penchant', definition:'A strong or habitual liking for something.', hint:'Fondness or preference', example:'She has a ___ for collecting rare books from the Victorian era.' },
    { term:'perfunctory', definition:'Carried out with a minimum of effort or reflection.', hint:'Done carelessly', example:'The inspector gave only a ___ glance at the documents before signing off.' },
    { term:'pertinent', definition:'Relevant or applicable to a particular matter.', hint:'Directly relevant', example:'The lawyer asked the witness to focus on facts ___ to the case.' },
    { term:'phlegmatic', definition:'Having an unemotional and calm disposition.', hint:'Calm and unexcitable', example:'His ___ demeanour under pressure made him an excellent crisis manager.' },
    { term:'placate', definition:'To make someone less angry or hostile; to appease.', hint:'Calm someone down', example:'The company offered refunds in an attempt to ___ dissatisfied customers.' },
    { term:'pragmatic', definition:'Dealing with things sensibly and realistically based on practical considerations.', hint:'Practical and sensible', example:'A ___ approach to the budget crisis meant cutting non-essential spending first.' },
    { term:'precarious', definition:'Not securely held or in position; dangerously likely to fall or collapse.', hint:'Unstable or risky', example:'Many workers in the gig economy face ___ employment with few protections.' },
    { term:'prodigal', definition:'Spending money or using resources freely and recklessly; wastefully extravagant.', hint:'Recklessly wasteful', example:'His ___ spending habits eventually left him unable to pay even basic expenses.' },
    { term:'profound', definition:'Very great or intense; having deep insight or understanding.', hint:'Deep or intense', example:'The discovery had a ___ impact on our understanding of the human genome.' },
    { term:'propensity', definition:'An inclination or natural tendency to behave in a particular way.', hint:'Natural tendency', example:'Studies suggest a ___ for risk-taking behaviour in adolescents compared to adults.' },
    { term:'querulous', definition:'Complaining in a whining manner.', hint:'Whiny and complaining', example:'The ___ tone of the letter suggested deep dissatisfaction with the service provided.' },
    { term:'recalcitrant', definition:'Having an obstinately uncooperative attitude.', hint:'Stubbornly uncooperative', example:'The ___ student refused to follow the classroom rules despite repeated warnings.' },
    { term:'reticent', definition:'Not revealing one\'s thoughts or feelings readily; reserved.', hint:'Reluctant to speak', example:'She was ___ about discussing her personal life during the interview.' },
    { term:'sagacious', definition:'Having or showing keen mental discernment and good judgement.', hint:'Wise and shrewd', example:'The ___ advisor anticipated the market downturn and adjusted the portfolio accordingly.' },
  ],

  'Low Frequency': [
    { term:'sanguine', definition:'Optimistic or positive, especially in a difficult situation.', hint:'Cheerfully optimistic', example:'Despite the setbacks, the project leader remained ___ about meeting the deadline.' },
    { term:'specious', definition:'Superficially plausible, but actually wrong; misleading in appearance.', hint:'Seems true but isn\'t', example:'The argument, though ___, fell apart under close examination by the panel.' },
    { term:'stolid', definition:'Calm, dependable, and showing little emotion or animation.', hint:'Unemotional and steady', example:'The ___ guard showed no reaction despite the chaotic scene unfolding before him.' },
    { term:'supplant', definition:'To supersede and replace.', hint:'Take the place of', example:'Digital media has largely ___ print newspapers as the primary source of daily news.' },
    { term:'sycophant', definition:'A person who acts obsequiously towards someone important to gain advantage.', hint:'Flattering follower', example:'The boardroom was filled with ___ who praised every decision the chairman made.' },
    { term:'taciturn', definition:'Reserved or uncommunicative in speech; saying little.', hint:'Speaks very little', example:'The ___ researcher preferred to let the data speak for itself rather than give interviews.' },
    { term:'tenuous', definition:'Very weak or slight; insubstantial.', hint:'Flimsy or weak', example:'The connection between the two events was ___ at best and did not withstand scrutiny.' },
    { term:'torpid', definition:'Mentally or physically inactive; sluggish.', hint:'Sluggish and inactive', example:'The ___ economy showed few signs of recovery despite government intervention.' },
    { term:'tractable', definition:'Easy to control or influence; manageable.', hint:'Easily managed', example:'The younger students proved more ___ and adapted quickly to the new curriculum.' },
    { term:'transient', definition:'Lasting only for a short time; temporary.', hint:'Short-lived', example:'The boom in housing prices proved to be ___, with values dropping sharply the following year.' },
    { term:'trepidation', definition:'A feeling of fear or anxiety about something that may happen.', hint:'Fearful anticipation', example:'She approached the final exam with considerable ___, having struggled with the material.' },
    { term:'truculent', definition:'Eager or quick to argue or fight; aggressively defiant.', hint:'Aggressively hostile', example:'The ___ attitude of the delegates made productive negotiations nearly impossible.' },
    { term:'ubiquitous', definition:'Present, appearing, or found everywhere.', hint:'Found everywhere', example:'Smartphones have become ___ in modern society, used by people of all ages.' },
    { term:'vacillate', definition:'To alternate or waver between different opinions or actions.', hint:'Go back and forth', example:'The committee continued to ___ between the two proposals, unable to reach a final decision.' },
    { term:'venerate', definition:'To regard with great respect; to revere.', hint:'Deeply respect', example:'The community continues to ___ the founder for her contributions to local education.' },
    { term:'verbose', definition:'Using or expressed in more words than are needed; wordy.', hint:'Uses too many words', example:'The report was unnecessarily ___, running to fifty pages when ten would have sufficed.' },
    { term:'vicarious', definition:'Experienced in the imagination through the feelings or actions of another person.', hint:'Through someone else', example:'She gained ___ satisfaction from watching her students achieve success in their careers.' },
    { term:'vindicate', definition:'To clear someone of blame or suspicion; to show to be right.', hint:'Prove right', example:'The final audit results served to ___ the finance team, who had been accused of mismanagement.' },
    { term:'visceral', definition:'Relating to deep inward feelings rather than to the intellect.', hint:'Deep gut feeling', example:'The documentary provoked a ___ reaction from audiences confronted with the harsh realities.' },
    { term:'voracious', definition:'Wanting or devouring great quantities; having a very eager approach.', hint:'Insatiably eager', example:'She was a ___ reader, often finishing several books in a single week.' },
    { term:'wanton', definition:'Deliberate and unprovoked; having no motive or reason.', hint:'Senseless or deliberate', example:'The ___ destruction of the ancient monument drew international condemnation.' },
    { term:'zealous', definition:'Having or showing great energy or enthusiasm in pursuit of a cause.', hint:'Passionately enthusiastic', example:'The ___ campaigners worked tirelessly to raise awareness of the environmental issue.' },
    { term:'abrogate', definition:'To repeal or do away with a law, right, or formal agreement.', hint:'Formally abolish', example:'The government moved to ___ the treaty that had been in place for over two decades.' },
    { term:'acerbic', definition:'Sharp and forthright in manner or speech, especially in a critical way.', hint:'Harshly critical', example:'The critic was known for her ___ reviews that spared no one, regardless of reputation.' },
    { term:'chicanery', definition:'The use of trickery to achieve a political, financial, or legal purpose.', hint:'Deception or trickery', example:'The investigation uncovered widespread ___ in the awarding of government contracts.' },
    { term:'circumscribe', definition:'To restrict or confine within limits.', hint:'Draw boundaries around', example:'The new regulations effectively ___ the powers of local planning authorities.' },
    { term:'coalesce', definition:'To come together to form one mass or whole.', hint:'Merge into one', example:'Several smaller protest groups began to ___ into a single unified movement.' },
    { term:'conflate', definition:'To combine two or more sets of information or ideas into one, often mistakenly.', hint:'Wrongly merge ideas', example:'It is a common error to ___ correlation with causation when interpreting data.' },
    { term:'demur', definition:'To raise objections or show reluctance.', hint:'Object politely', example:'When asked to take on additional duties without extra pay, she chose to ___.' },
    { term:'enervate', definition:'To cause someone to feel drained of energy; to weaken.', hint:'Drain of energy', example:'The prolonged heatwave continued to ___ both workers and livestock across the region.' },
    { term:'fractious', definition:'Irritable and quarrelsome; difficult to control.', hint:'Easily angered', example:'The ___ debate between the candidates offered little substance and much confrontation.' },
    { term:'gossamer', definition:'Used to describe something very light, thin, or insubstantial.', hint:'Extremely delicate', example:'The ___ fabric of the curtain allowed sunlight to filter gently into the room.' },
    { term:'hegemony', definition:'Leadership or dominance, especially by one state or social group over others.', hint:'Dominant authority', example:'The nation maintained its economic ___ in the region for several decades.' },
    { term:'inveigle', definition:'To persuade someone to do something by means of deception or flattery.', hint:'Coax or sweet-talk', example:'He managed to ___ his way into the exclusive event by charming the organisers.' },
    { term:'nonplussed', definition:'Surprised and confused so much that one is unsure how to react.', hint:'Baffled and unsure', example:'The audience was ___ by the speaker\'s sudden departure from the stage mid-sentence.' },
    { term:'pellucid', definition:'Translucently clear; easily understood.', hint:'Crystal clear', example:'The author\'s ___ prose made even the most complex philosophical ideas accessible to all.' },
    { term:'probity', definition:'The quality of having strong moral principles; honesty and decency.', hint:'Moral integrity', example:'A judge must be a person of unquestionable ___ to maintain public trust in the courts.' },
    { term:'recondite', definition:'Little known; abstruse; dealing with obscure subject matter.', hint:'Obscure and hard to grasp', example:'The lecture covered ___ aspects of quantum mechanics that were beyond most attendees.' },
    { term:'verisimilitude', definition:'The appearance of being true or real.', hint:'Seeming real or true', example:'The historical novel achieved a remarkable degree of ___ through its meticulous research.' },
    { term:'vituperate', definition:'To blame or insult someone in strong or violent language.', hint:'Bitterly criticise', example:'The editorial chose to ___ the officials responsible for the policy failure.' },
  ],
};
